/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Controllers.ArticuloController;
import Models.Articulo;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author franco-lxle
 */
public class ModificarArticuloUI extends javax.swing.JFrame {
    
    //Instancia de la clase que da soporte a la interfaz
    ModificarArticuloHelper helper = new ModificarArticuloHelper();
    //Instancia de Articulo a modificar
    Articulo art;
    //Instancia de Articulo modificado
    Articulo artModificado;

    /**
     * Creates new form AltaArticuloUI
     */
    public ModificarArticuloUI() {
        initComponents();
        
        //Por defecto activo debe estar seleccionado
        chb_activo.setSelected(true);
        //Obtengo las instancias de los tipos que existen y las añado al selector
        ArrayList<String> tipos = helper.getTipos();
        for (int i = 0; i < tipos.size(); i++) {
            cb_tipoArticulo.addItem(tipos.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_codArticulo = new javax.swing.JLabel();
        lbl_descripcion = new javax.swing.JLabel();
        lbl_activo = new javax.swing.JLabel();
        lbl_unidadMedida = new javax.swing.JLabel();
        lbl_tipoArticulo = new javax.swing.JLabel();
        cb_tipoArticulo = new javax.swing.JComboBox<>();
        chb_activo = new javax.swing.JCheckBox();
        txt_codArticulo = new javax.swing.JTextField();
        txt_descripcion = new javax.swing.JTextField();
        txt_unidadMedida = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_modificar = new javax.swing.JButton();
        btn_buscarArt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_codArticulo.setText("Código del artículo");

        lbl_descripcion.setText("Descripcion");

        lbl_activo.setText("Activo");

        lbl_unidadMedida.setText("Unidad de Medida");

        lbl_tipoArticulo.setText("Tipo de Artículo");

        cb_tipoArticulo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));

        chb_activo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_activoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Modificar Artículo");

        btn_modificar.setText("OK");
        btn_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modificarMouseClicked(evt);
            }
        });

        btn_buscarArt.setText("Buscar");
        btn_buscarArt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_buscarArtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_unidadMedida)
                                    .addComponent(lbl_tipoArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_activo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(chb_activo)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txt_unidadMedida)
                                    .addComponent(cb_tipoArticulo, 0, 300, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_descripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_codArticulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_descripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                                    .addComponent(txt_codArticulo))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(btn_buscarArt))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_modificar)))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_codArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_codArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscarArt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_activo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chb_activo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_unidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_unidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lbl_tipoArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cb_tipoArticulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(btn_modificar)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chb_activoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_activoActionPerformed
    }//GEN-LAST:event_chb_activoActionPerformed

    private void btn_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificarMouseClicked
        
        String codArticulo = txt_codArticulo.getText();
        String descripcion = txt_descripcion.getText();
        boolean activo = chb_activo.isSelected();
        String unidadMedida = txt_unidadMedida.getText();
        //Primero busco el id del obj seleccionado en el selector y después busco el id del tipoArticulo en la tabla hash
        int indexSeleccionado = cb_tipoArticulo.getSelectedIndex();
        int idTipoArticulo = helper.getTipoIdFromIndex(indexSeleccionado);
        if (!codArticulo.isEmpty() && !descripcion.isEmpty() && !unidadMedida.isEmpty() ){
            artModificado = new Articulo();
            artModificado.setCodArticulo(codArticulo);
            artModificado.setDescripcion(descripcion);
            artModificado.setActivo(activo);
            artModificado.setUnidadMedida(unidadMedida);
            artModificado.setIdTipoArticulo(idTipoArticulo);
            if (helper.existenCambios(art, artModificado)){
                int idArticulo = art.getIdArticulo();
                artModificado.setIdArticulo(idArticulo);
                helper.modificar(artModificado);
                art = artModificado;
            }
            else {JOptionPane.showMessageDialog(this, "No se han realizado cambios");}
        
        }
        else {JOptionPane.showMessageDialog(this, "Faltan campos por completar");}
    }//GEN-LAST:event_btn_modificarMouseClicked

    private void btn_buscarArtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarArtMouseClicked
        String codArticulo = txt_codArticulo.getText();
        if (codArticulo.isEmpty()){ //no se ha colocado un cod
            JOptionPane.showMessageDialog(this, "Ingrese un código");
        }
        else { //Hay código
            if (helper.codigoExiste(codArticulo)){ // El código existe
                art = helper.buscarArticulo(codArticulo);
                txt_descripcion.setText(art.getDescripcion());
                chb_activo.setSelected(art.isActivo());
                txt_unidadMedida.setText(art.getUnidadMedida());
                cb_tipoArticulo.setSelectedIndex(art.getIdTipoArticulo()-1);
            }
            else { // El código no existe
                JOptionPane.showMessageDialog(this, "El código ingresado no existe");
            }
        }
        
    }//GEN-LAST:event_btn_buscarArtMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscarArt;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JComboBox<String> cb_tipoArticulo;
    private javax.swing.JCheckBox chb_activo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_activo;
    private javax.swing.JLabel lbl_codArticulo;
    private javax.swing.JLabel lbl_descripcion;
    private javax.swing.JLabel lbl_tipoArticulo;
    private javax.swing.JLabel lbl_unidadMedida;
    private javax.swing.JTextField txt_codArticulo;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_unidadMedida;
    // End of variables declaration//GEN-END:variables
}
