/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Models.Producto;
import java.sql.Array;
import java.util.HashMap;
import java.util.Arrays;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author franco
 */
public class AltaEstructuraUI extends javax.swing.JFrame {
    
    //Instancia de helper
    AltaEstructuraHelper helper = new AltaEstructuraHelper();
    //Instancia de producto
    Producto prod;
    //HashMap para mantener asociados los articulos a los ID
    HashMap<String, Integer> articulos;

    /**
     * Creates new form AltaEstructuraUI
     */
    public AltaEstructuraUI() {
        initComponents();
        chb_activo.setSelected(true);
        lbl_descripcion.setText(""); //Para no perderlo al momento de diseñar, se pone en blanco al iniciar
        articulos = helper.obtenerArticulos();
        DefaultListModel<String> model = new DefaultListModel();
        for(String desc : articulos.keySet()){
            model.addElement(desc);
        }
        list_arts.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_codProd = new javax.swing.JLabel();
        txt_codProducto = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        lbl_descripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_arts = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        btn_añadir = new javax.swing.JButton();
        btn_quitar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_artsSelec = new javax.swing.JTable();
        lbl_version = new javax.swing.JLabel();
        txt_version = new javax.swing.JTextField();
        lbl_activo = new javax.swing.JLabel();
        chb_activo = new javax.swing.JCheckBox();
        btn_alta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Alta Estructura");

        lbl_codProd.setText("Código de producto");

        btn_buscar.setText("Buscar");
        btn_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_buscarMouseClicked(evt);
            }
        });

        lbl_descripcion.setText("placeholder");

        list_arts.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(list_arts);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Artículos");

        btn_añadir.setText("🡺");
        btn_añadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_añadirMouseClicked(evt);
            }
        });

        btn_quitar.setText("🡸");
        btn_quitar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_quitarMouseClicked(evt);
            }
        });

        tb_artsSelec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Articulo", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tb_artsSelec.setColumnSelectionAllowed(true);
        tb_artsSelec.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tb_artsSelec);
        tb_artsSelec.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tb_artsSelec.getColumnModel().getColumnCount() > 0) {
            tb_artsSelec.getColumnModel().getColumn(0).setResizable(false);
            tb_artsSelec.getColumnModel().getColumn(1).setResizable(false);
        }

        lbl_version.setText("Version");

        txt_version.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_versionActionPerformed(evt);
            }
        });

        lbl_activo.setText("Activo");

        btn_alta.setText("OK");
        btn_alta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_altaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_codProd)
                        .addGap(18, 18, 18)
                        .addComponent(txt_codProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_buscar)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_activo)
                                .addGap(18, 18, 18)
                                .addComponent(chb_activo))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lbl_version)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_version))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_añadir)
                                            .addComponent(btn_quitar))
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_alta, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(70, 70, 70)))))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_codProd)
                    .addComponent(txt_codProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar)
                    .addComponent(lbl_descripcion))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btn_añadir)
                        .addGap(18, 18, 18)
                        .addComponent(btn_quitar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_activo)
                    .addComponent(chb_activo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_version)
                    .addComponent(txt_version, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_alta))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarMouseClicked
        String codProducto = txt_codProducto.getText();
        if (codProducto.isEmpty()){ //no se ha colocado un cod
            JOptionPane.showMessageDialog(this, "Ingrese un código");
        }else { //Hay código
            if (helper.codigoExiste(codProducto)){ // El código existe
                prod = helper.buscarProducto(codProducto);
                lbl_descripcion.setText(prod.getDescripcion());
            }
            else { // El código no existe
                JOptionPane.showMessageDialog(this, "El código ingresado no existe");
            }
        }
    }//GEN-LAST:event_btn_buscarMouseClicked

    private void btn_añadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_añadirMouseClicked
        if(list_arts.isSelectionEmpty()){
            JOptionPane.showMessageDialog(this, "Seleccione un artículo");
            return;
        }
        
        //Añade a la tabla
        String descr = list_arts.getSelectedValue();
        DefaultTableModel tmodel = (DefaultTableModel)tb_artsSelec.getModel();
        tmodel.addRow(new Object[]{descr});

        //Quita de la lista
        int index = list_arts.getSelectedIndex();
        DefaultListModel<String> lmodel = (DefaultListModel) list_arts.getModel();
        lmodel.removeElementAt(index);
    }//GEN-LAST:event_btn_añadirMouseClicked

    private void btn_quitarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_quitarMouseClicked
        if(tb_artsSelec.getSelectedRow() < 0){ //Si no hay fila seleccionada devuelve -1
            JOptionPane.showMessageDialog(this, "Seleccione un artículo");
            return;
        }
        
        //Añade a la lista
        int row = tb_artsSelec.getSelectedRow();
        String descr = String.valueOf(tb_artsSelec.getValueAt(row, 0)); //La columna siempre es 0
        DefaultListModel<String> lmodel = (DefaultListModel) list_arts.getModel();
        lmodel.addElement(descr);
        //Las próximas líneas sirven para reordenar la lista una vez que se añade el elemento
        String[] array = Arrays.copyOf(lmodel.toArray(), lmodel.toArray().length, String[].class);
        Arrays.sort(array);
        list_arts.setListData(array);
        
        //Quita de la tabla
        DefaultTableModel tmodel = (DefaultTableModel)tb_artsSelec.getModel();
        tmodel.removeRow(row);

    }//GEN-LAST:event_btn_quitarMouseClicked

    private void txt_versionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_versionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_versionActionPerformed

    private void btn_altaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_altaMouseClicked
        if(prod == null){
            JOptionPane.showMessageDialog(this, "Debe buscar un producto");
            return;
        }
        
        if(tb_artsSelec.getModel().getRowCount() == 0){
            JOptionPane.showMessageDialog(this, "Debe añadir al menos un artículo");
            return;
        }
        //Chequeo que cantidad esté indicado para todas las filas
        DefaultTableModel model = (DefaultTableModel) tb_artsSelec.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            if(model.getValueAt(i, 1) == null){
                JOptionPane.showMessageDialog(this, "Debe especificar cantidad para todos los artículos");
                return;
            }
        }
        
        String version = txt_version.getText();
        if(version.isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe especificar la version");
            return;
        }
        boolean activo = chb_activo.isSelected();
        HashMap<Integer, Integer> detEst = new HashMap<Integer, Integer>();
        int idArt;
        int cantidad;
        String desc;
        for (int i = 0; i < model.getRowCount(); i++) {
            desc = (String) model.getValueAt(i, 0);
            idArt = obtenerID(desc);
            cantidad = (int) model.getValueAt(i, 1);
            detEst.put(idArt, cantidad);
        }
        
        helper.altaEstructura(prod.getIdProducto(), activo, version, detEst);
        JOptionPane.showMessageDialog(this, "Alta Satisfactoria");
    }//GEN-LAST:event_btn_altaMouseClicked
  
    private int obtenerID(String desc){
        return articulos.get(desc);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alta;
    private javax.swing.JButton btn_añadir;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_quitar;
    private javax.swing.JCheckBox chb_activo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_activo;
    private javax.swing.JLabel lbl_codProd;
    private javax.swing.JLabel lbl_descripcion;
    private javax.swing.JLabel lbl_version;
    private javax.swing.JList<String> list_arts;
    private javax.swing.JTable tb_artsSelec;
    private javax.swing.JTextField txt_codProducto;
    private javax.swing.JTextField txt_version;
    // End of variables declaration//GEN-END:variables
}
