/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Controllers.ArticuloController;
import Models.Producto;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author franco-lxle
 */
public class BajaProductoUI extends javax.swing.JFrame {

    //Instancia de la clase que da soporte a la interfaz
    BajaProductoHelper helper = new BajaProductoHelper();
    //Instancias de Producto
    Producto prod;

    /**
     * Creates new form AltaArticuloUI
     */
    public BajaProductoUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_codArticulo = new javax.swing.JLabel();
        txt_codArticulo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_baja = new javax.swing.JButton();
        btn_buscarProd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_producto = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_codArticulo.setText("Código del producto");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Baja Producto");

        btn_baja.setText("OK");
        btn_baja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_bajaMouseClicked(evt);
            }
        });
        btn_baja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bajaActionPerformed(evt);
            }
        });

        btn_buscarProd.setText("Buscar");
        btn_buscarProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_buscarProdMouseClicked(evt);
            }
        });

        tb_producto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Descripcion", "Activo", "Unidad de Medida", "Producto Base", "Producto Padre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Boolean.class, java.lang.String.class, java.lang.Boolean.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_producto.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tb_producto);
        if (tb_producto.getColumnModel().getColumnCount() > 0) {
            tb_producto.getColumnModel().getColumn(0).setResizable(false);
            tb_producto.getColumnModel().getColumn(1).setResizable(false);
            tb_producto.getColumnModel().getColumn(2).setResizable(false);
            tb_producto.getColumnModel().getColumn(3).setResizable(false);
            tb_producto.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_baja))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_codArticulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_codArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                        .addComponent(btn_buscarProd)))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_codArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_codArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscarProd))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(btn_baja)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_bajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bajaMouseClicked
        if (prod == null) {
            JOptionPane.showMessageDialog(this, "No hay un producto buscado");
            return;
        }
        if (prod.getIdTipoProducto() == 1) { // Si es producto base
            if (helper.tieneProductosFinales(prod.getIdProducto())) { //verfico que no tenga productos que dependan de él
                JOptionPane.showMessageDialog(this, "El producto tiene productos finales dependientes.");
                return;
            }
        }
        if (!helper.tieneOrdenesPendientes(prod.getIdProducto())) { //verifico que no tenga ordenes de produccion pendientes o activas
            //Custom button text
            Object[] options = {"Dar baja",
                "Cancelar"};
            int opcion = JOptionPane.showOptionDialog(this,
                    "Al dar de baja un producto, también se da de baja "
                    + " sus rutas y estructuras",
                    "Continuar",
                    JOptionPane.YES_NO_CANCEL_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    options,
                    options[1]);
            //Opcion = 1 es cancelar, opcion = 0 es dar baja
            if (opcion == 0) {
                helper.bajaProducto(prod.getIdProducto());
                prod = null;
                JOptionPane.showMessageDialog(this, "Baja satisfactoria");
            } else {
                return;
            }
        } else {
            JOptionPane.showMessageDialog(this, "El producto tiene orden(es) de producción pendiente");
        }
    }//GEN-LAST:event_btn_bajaMouseClicked

    private void btn_buscarProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarProdMouseClicked
        String codProducto = txt_codArticulo.getText();
        if (codProducto.isEmpty()) { //no se ha colocado un cod
            JOptionPane.showMessageDialog(this, "Ingrese un código");
        } else { //Hay código
            if (helper.codigoExiste(codProducto)) { // El código existe
                prod = helper.buscarProducto(codProducto);
                if (prod.isActivo()) {
                    tb_producto.setValueAt(prod.getDescripcion(), 0, 0);
                    tb_producto.setValueAt(prod.isActivo(), 0, 1);
                    tb_producto.setValueAt(prod.getUnidadMedida(), 0, 2);
                    boolean isProdBase;
                    if (prod.getIdTipoProducto() == 1) {
                        isProdBase = true;
                    } else {
                        isProdBase = false;
                    }
                    tb_producto.setValueAt(isProdBase, 0, 3);
                    if (prod.getIdProductoBase() == 0) {
                        tb_producto.setValueAt("Ninguno", 0, 4);
                    } else {
                        tb_producto.setValueAt(helper.obtenerDescProdPadre(prod.getIdProductoBase()), 0, 4);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "El producto ya está inactivo");
                }

            } else { // El código no existe
                JOptionPane.showMessageDialog(this, "El código ingresado no existe");
            }
        }
    }//GEN-LAST:event_btn_buscarProdMouseClicked

    private void btn_bajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_bajaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_baja;
    private javax.swing.JButton btn_buscarProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_codArticulo;
    private javax.swing.JTable tb_producto;
    private javax.swing.JTextField txt_codArticulo;
    // End of variables declaration//GEN-END:variables
}
