/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Models.Estructura;
import Models.Producto;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author franco-deb
 */
public class BajaEstructuraUI extends javax.swing.JFrame {

    //Instancia del helper
    BajaEstructuraHelper helper = new BajaEstructuraHelper();
    //Instancia del Producto
    Producto prod;
    //Instancias de Estructura
    ArrayList<Estructura> estructuras;
    //Instancias de Estructura que van a darse de baja
    ArrayList<Estructura> estructurasABajar = new ArrayList();
    //Listado de versiones
    ArrayList<String> versiones = new ArrayList();
    //Version elegida
    String versionElegida = "";
    //Referencia al modelo de la tabla
    DefaultTableModel tmodel;

    /**
     * Creates new form BajaEstructuraUI
     */
    public BajaEstructuraUI() {
        initComponents();
        tmodel = (DefaultTableModel) tb_detalleEstructura.getModel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_codProducto = new javax.swing.JTextField();
        btn_buscarProd = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cb_versiones = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_detalleEstructura = new javax.swing.JTable();
        btn_darBaja = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Baja de Estructura");

        jLabel2.setText("Código del producto");

        btn_buscarProd.setText("Buscar");
        btn_buscarProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_buscarProdMouseClicked(evt);
            }
        });

        jLabel3.setText("Estructura");

        cb_versiones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        cb_versiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_versionesActionPerformed(evt);
            }
        });

        jLabel4.setText("Detalle");

        tb_detalleEstructura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Articulo", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_detalleEstructura.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tb_detalleEstructura);
        if (tb_detalleEstructura.getColumnModel().getColumnCount() > 0) {
            tb_detalleEstructura.getColumnModel().getColumn(0).setResizable(false);
            tb_detalleEstructura.getColumnModel().getColumn(1).setResizable(false);
        }

        btn_darBaja.setText("Dar baja");
        btn_darBaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_darBajaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_codProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_buscarProd))
                            .addComponent(cb_versiones, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_darBaja)
                        .addGap(47, 47, 47))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_codProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscarProd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cb_versiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_darBaja))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscarProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarProdMouseClicked
        //limpio los elementos gráficos
        tmodel.setRowCount(0);
        cb_versiones.removeAllItems();
        //Busco el prod con el cual voy a trabajar
        String codProducto = txt_codProducto.getText();
        if (codProducto.isEmpty()) { //no se ha colocado un cod
            JOptionPane.showMessageDialog(this, "Ingrese un código");
            return;
        } else //Hay código
        if (helper.codigoExiste(codProducto)) { // El código existe
            prod = helper.buscarProducto(codProducto);
        } else { // El código no existe
            JOptionPane.showMessageDialog(this, "El código ingresado no existe");
            return;
        }

        //Busco las estructuras del producto
        estructuras = helper.obtenerVersionesEstructura(prod.getIdProducto());
        buscarVersiones();
        if (estructuras.size() > 0) {
            cb_versiones.addItem("Elegir version...");
            for (String version : versiones) {
                cb_versiones.addItem(version);
            }
        } else {
            JOptionPane.showMessageDialog(this, "El producto no tiene estructuras activas");
            return;
        }
    }//GEN-LAST:event_btn_buscarProdMouseClicked

    private void cb_versionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_versionesActionPerformed
        if (cb_versiones.getSelectedIndex() == 0) {
            tmodel.setRowCount(0);
            versionElegida = "";
            return;
        }
        versionElegida = String.valueOf(cb_versiones.getSelectedItem());
        poblarTabla();

    }//GEN-LAST:event_cb_versionesActionPerformed

    private void btn_darBajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_darBajaMouseClicked
        if (prod == null){
            JOptionPane.showMessageDialog(this, "Busque un producto primero");
            return;
        }
        if (cb_versiones.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(this, "Seleccione una version");
            return;
        }
        
        if (helper.tieneOrdenesPendientes(prod.getIdProducto())){
            JOptionPane.showMessageDialog(this, "El producto tiene ordenes de produccion pendientes");
            return;
        }
        
        for (Estructura est : estructurasABajar){
            helper.bajaEstructura(est.getIdEstructura());
        }
        JOptionPane.showMessageDialog(this, "Baja satisfactoria");
    }//GEN-LAST:event_btn_darBajaMouseClicked

    private void buscarVersiones() {
        for (Estructura est : estructuras) {
            if (!versiones.contains(est.getVersion())) { //Si en el listado no está la version de esta estructura, lo agrega
                versiones.add(est.getVersion());
            }
        }
    }

    private void poblarTabla() {
        tmodel.setRowCount(0); //limpio la tabla
        int row = 0;
        for (Estructura est : estructuras){
            if (est.getVersion().equals(versionElegida)){
                estructurasABajar.add(est);
                Object[] fila = new Object[]{helper.obtenerArt(est.getIdArticulo()), est.getCantidad()};
                tmodel.addRow(fila);
                row++;
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscarProd;
    private javax.swing.JButton btn_darBaja;
    private javax.swing.JComboBox<String> cb_versiones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_detalleEstructura;
    private javax.swing.JTextField txt_codProducto;
    // End of variables declaration//GEN-END:variables
}
